const STORAGE_KEY = 'invoicedey-v1';
const today = () => new Date().toISOString().slice(0, 10);
const inThirtyDays = () => { const d = new Date(); d.setDate(d.getDate() + 30); return d.toISOString().slice(0, 10); };
const seed = { business: { name: 'My business', email: '', address: '', currency: 'USD', prefix: 'INV' }, clients: [{ id: 'client_1', name: 'Northstar Creative', email: 'accounts@northstar.example', address: '' }], invoices: [{ id: 'invoice_demo', number: 'INV-0001', clientId: 'client_1', issueDate: today(), dueDate: inThirtyDays(), currency: 'USD', status: 'draft', taxRate: 0, lines: [{ description: 'Brand strategy workshop', quantity: 1, rate: 1200 }] }] };
let state;
try { state = JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(seed); } catch { state = structuredClone(seed); }
const $ = (s) => document.querySelector(s);
const money = (value, currency = state.business.currency) => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value || 0);
const total = (invoice) => invoice.lines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.rate || 0), 0) * (1 + Number(invoice.taxRate || 0) / 100);
const clientFor = (invoice) => state.clients.find((c) => c.id === invoice.clientId) || { name: 'Unknown client' };
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); };
const escape = (v = '') => String(v).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[c]));

function navigate(page) { document.querySelectorAll('.page').forEach((el) => el.classList.toggle('active', el.id === page)); document.querySelectorAll('[data-page]').forEach((el) => el.classList.toggle('active', el.dataset.page === page)); const title = { dashboard: 'Good morning', invoices: 'Invoices', clients: 'Clients', settings: 'Business settings' }[page]; $('#pageTitle').textContent = title; $('#pageEyebrow').textContent = page.toUpperCase(); $('#menuButton').closest('.shell').querySelector('.sidebar').classList.remove('open'); render(); }
function statusFor(invoice) { if (invoice.status === 'paid') return 'paid'; return invoice.status === 'sent' && invoice.dueDate < today() ? 'overdue' : invoice.status; }
function renderMetrics() { const sent = state.invoices.filter((i) => i.status === 'sent' || i.status === 'overdue'); const overdue = sent.filter((i) => i.dueDate < today()); const paid = state.invoices.filter((i) => i.status === 'paid'); const due = sent.reduce((s, i) => s + total(i), 0); $('#metrics').innerHTML = [["Outstanding", money(due), `${sent.length} invoice${sent.length === 1 ? '' : 's'} awaiting payment`], ['Overdue', money(overdue.reduce((s, i) => s + total(i), 0)), `${overdue.length} invoice${overdue.length === 1 ? '' : 's'} need attention`], ['Paid this month', money(paid.reduce((s, i) => s + total(i), 0)), `${paid.length} payments recorded`], ['Drafts', state.invoices.filter((i) => i.status === 'draft').length, 'Ready to review and send']].map(([label, value, helper]) => `<article class="metric"><p>${label}</p><h3>${value}</h3><small>${helper}</small></article>`).join(''); }
function invoiceRows(items, compact = false) { if (!items.length) return `<div class="empty"><h3>No invoices yet</h3><p>Create your first invoice and start getting paid.</p></div>`; return items.map((invoice) => { const client = clientFor(invoice); const s = statusFor(invoice); return compact ? `<div class="invoice-row"><div><b>${escape(invoice.number)}</b><small>${escape(client.name)} · Due ${escape(invoice.dueDate)}</small></div><span class="pill ${s}">${s}</span><b class="right">${money(total(invoice), invoice.currency)}</b><button class="text-button right" data-paid="${invoice.id}">${s === 'paid' ? 'Paid' : 'Mark paid'}</button></div>` : `<div class="table-row"><div><b>${escape(invoice.number)}</b><small>${escape(client.name)}</small></div><div>${escape(invoice.issueDate)}<small>Due ${escape(invoice.dueDate)}</small></div><div><span class="pill ${s}">${s}</span></div><b>${money(total(invoice), invoice.currency)}</b><button class="text-button" data-paid="${invoice.id}">${s === 'paid' ? 'Paid' : 'Mark paid'}</button></div>`; }).join(''); }
function renderInvoices() { const query = ($('#invoiceSearch')?.value || '').toLowerCase(); const items = state.invoices.filter((i) => `${i.number} ${clientFor(i).name} ${i.status}`.toLowerCase().includes(query)); $('#invoiceTable').innerHTML = `<div class="table-head"><span>Invoice</span><span>Dates</span><span>Status</span><span>Amount</span><span></span></div>${invoiceRows(items)}`; }
function renderClients() { $('#clientTable').innerHTML = state.clients.length ? `<div class="table-head"><span>Client</span><span>Email</span><span>Invoices</span><span></span><span></span></div>${state.clients.map((client) => { const count = state.invoices.filter((i) => i.clientId === client.id).length; return `<div class="table-row"><div><b>${escape(client.name)}</b><small>${escape(client.address || 'No address')}</small></div><div>${escape(client.email || '—')}</div><div>${count}</div></div>`; }).join('')}` : `<div class="empty"><h3>No clients saved</h3><p>Add your first client to invoice them faster.</p></div>`; }
function renderDashboard() { renderMetrics(); $('#recentInvoices').innerHTML = invoiceRows(state.invoices.slice(0, 5), true); const overdue = state.invoices.filter((i) => statusFor(i) === 'overdue'); $('#insight').innerHTML = overdue.length ? `<div class="insight-box"><h3>${overdue.length} overdue invoice${overdue.length > 1 ? 's' : ''}</h3><p>Reach out today to keep cash flowing.</p></div>` : `<div class="insight-box"><h3>You’re in good shape</h3><p>No overdue invoices. Keep the momentum going.</p></div>`; }
function render() { $('#businessNameSmall').textContent = state.business.name || 'My business'; const form = $('#settingsForm'); if (form) Object.entries(state.business).forEach(([key, value]) => form.elements[key] && (form.elements[key].value = value)); renderDashboard(); renderInvoices(); renderClients(); document.querySelectorAll('[data-paid]').forEach((btn) => btn.onclick = () => { const invoice = state.invoices.find((i) => i.id === btn.dataset.paid); if (invoice && invoice.status !== 'paid') { invoice.status = 'paid'; save(); render(); toast(`${invoice.number} marked as paid.`); } }); }
function lineElement(line = { description: '', quantity: 1, rate: 0 }) { const row = document.createElement('div'); row.className = 'line-item'; row.innerHTML = `<input required name="description" placeholder="Description" value="${escape(line.description)}"><input required name="quantity" type="number" min="0" step="0.01" value="${line.quantity}"><input required name="rate" type="number" min="0" step="0.01" value="${line.rate}"><button type="button" class="remove-line" aria-label="Remove line">×</button>`; row.querySelector('.remove-line').onclick = () => { row.remove(); recalculate(); }; row.querySelectorAll('input').forEach((input) => input.oninput = recalculate); return row; }
function recalculate() { const lines = [...document.querySelectorAll('.line-item')].map((row) => ({ quantity: Number(row.elements.quantity.value || 0), rate: Number(row.elements.rate.value || 0) })); const subtotal = lines.reduce((sum, line) => sum + line.quantity * line.rate, 0); const tax = subtotal * Number($('#taxRate').value || 0) / 100; const currency = $('#invoiceCurrency').value; $('#subtotal').textContent = money(subtotal, currency); $('#taxTotal').textContent = money(tax, currency); $('#invoiceTotal').textContent = money(subtotal + tax, currency); }
function openInvoice() { const form = $('#invoiceForm'); form.reset(); const clientSelect = $('#invoiceClient'); clientSelect.innerHTML = state.clients.length ? state.clients.map((c) => `<option value="${c.id}">${escape(c.name)}</option>`).join('') : '<option value="">Add a client first</option>'; form.elements.clientId.disabled = !state.clients.length; const next = state.invoices.length + 1; $('#invoiceNumber').value = `${state.business.prefix || 'INV'}-${String(next).padStart(4, '0')}`; form.elements.issueDate.value = today(); form.elements.dueDate.value = inThirtyDays(); $('#invoiceCurrency').value = state.business.currency; $('#lineItems').replaceChildren(lineElement()); recalculate(); $('#invoiceDialog').showModal(); }

document.querySelectorAll('[data-page]').forEach((el) => el.onclick = () => navigate(el.dataset.page)); $('#menuButton').onclick = () => $('.sidebar').classList.toggle('open'); ['newInvoice', 'welcomeInvoice', 'listNewInvoice'].forEach((id) => $(`#${id}`).onclick = openInvoice); $('#newClient').onclick = () => $('#clientDialog').showModal(); $('#addLine').onclick = () => { $('#lineItems').append(lineElement()); recalculate(); }; $('#taxRate').oninput = recalculate; $('#invoiceCurrency').onchange = recalculate; $('#invoiceSearch').oninput = renderInvoices;
$('#clientForm').onsubmit = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); state.clients.push({ id: `client_${crypto.randomUUID()}`, ...values }); save(); event.currentTarget.closest('dialog').close(); render(); toast('Client saved.'); };
$('#invoiceForm').onsubmit = (event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); if (!values.clientId) return toast('Add a client before creating an invoice.'); const lines = [...$('#lineItems').querySelectorAll('.line-item')].map((row) => ({ description: row.elements.description.value.trim(), quantity: Number(row.elements.quantity.value), rate: Number(row.elements.rate.value) })).filter((line) => line.description); if (!lines.length) return toast('Add at least one line item.'); state.invoices.unshift({ id: `invoice_${crypto.randomUUID()}`, ...values, taxRate: Number($('#taxRate').value), lines }); save(); form.closest('dialog').close(); render(); navigate('invoices'); toast('Invoice saved.'); };
$('#settingsForm').onsubmit = (event) => { event.preventDefault(); state.business = { ...state.business, ...Object.fromEntries(new FormData(event.currentTarget)) }; save(); render(); toast('Business settings saved.'); };
render();
